# config/packages/doctrine.yaml

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # Pour PostgreSQL, décommenter la ligne ci-dessous :
        # server_version: '15'

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware

        auto_mapping: true
        mappings:
            Leave:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Leave/Domain/Entity'
                prefix: 'App\Leave\Domain\Entity'
                alias: Leave

            Security:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Security/Entity'
                prefix: 'App\Security\Entity'
                alias: Security

when@test:
    doctrine:
        dbal:
            url: 'sqlite:///:memory:'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
